### ISSUE TITLE
HomeBrew tap: Error: Cannot tap incu6us/tap: invalid syntax in tap!

### ISSUE THREAD

**Issue by missylbytes** [incu6us/goimports-reviser#30]
Trying to install based off of the instructions in the readme, i.e.
`brew tap incu6us/homebrew-tap
brew install incu6us/homebrew-tap/goimports-reviser`

When I run brew tap, I get the following:

```
brew tap incu6us/homebrew-tap
==> Tapping incu6us/tap
Cloning into '/usr/local/Homebrew/Library/Taps/incu6us/homebrew-tap'...
remote: Enumerating objects: 115, done.
remote: Counting objects: 100% (115/115), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 115 (delta 27), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (115/115), 14.32 KiB | 3.58 MiB/s, done.
Resolving deltas: 100% (27/27), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/incu6us/homebrew-tap/Formula/ckafka.rb
formulae require at least a URL
Error: Cannot tap incu6us/tap: invalid syntax in tap!
```

HomeBrew Version: 2.5.11

**Comment by incu6us** [comment]
@missylbytes thanks for the issue!
Please, try now. It should work now

**Comment by missylbytes** [comment]
Yes it is working. Thank you!

**Comment by casimcdaniels** [comment]
@incu6us This seems to be happening again on version 3.3.5

```
Please report this issue to the incu6us/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/incu6us/homebrew-tap/Formula/goimports-reviser.rb:9

Error: Invalid formula: /opt/homebrew/Library/Taps/incu6us/homebrew-tap/Formula/goimports-reviser.rb
formulae require at least a URL
Error: Cannot tap incu6us/tap: invalid syntax in tap!
/opt/homebrew/Library/Homebrew/tap.rb:308:in `install'
/opt/homebrew/Library/Homebrew/cmd/tap.rb:67:in `tap'
/opt/homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by incu6us** [comment]
@casimcdaniels there were some changes in homebrew. Updated the *.rb file. Try to do `brew update` and it will work

**Comment by daregod** [comment]
Work fine on intel macbook, but on M1:

```
Error: Invalid formula: /opt/homebrew/Library/Taps/incu6us/homebrew-tap/Formula/goimports-reviser.rb
formulae require at least a URL
Error: Cannot tap incu6us/tap: invalid syntax in tap!
```

brew update didnt help

**Comment by incu6us** [comment]
@daregod try to use `go install github.com/incu6us/goimports-reviser` instead of brew for M1
